---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  KUBE_VIP_ADDR: "10.6.40.70"
  METALLB_LB_RANGE: "10.6.40.80-10.6.40.99"
  METALLB_K8S_GATEWAY_ADDR: "10.6.40.90"
  METALLB_INGRESS_ADDR: "10.6.40.80"
